"""build_data.py — bundle the plan for the offline web dashboard.

Reads deliverables/prescription.json and writes web/data.js:

    window.PLAN = { ...the full plan... };
    window.PROMO_RESPONSE = { category: [a, b], ... };   // for the what-if slider
    window.PROMO_BUDGET = 40000;

The promo response (a, b) parameters are pulled from the *same* function the
optimizer uses (`revops.optimize.promo._category_response`) so the client-side
"what-if" slider mirrors the real concave-allocation formula exactly.

    python -m revops.report        # writes deliverables/prescription.json
    python web/build_data.py       # writes web/data.js  ->  open web/index.html

Author: Dimitres Kisimov.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:                    # allow `python web/build_data.py`
    sys.path.insert(0, str(_ROOT))
_PLAN = _ROOT / "deliverables" / "prescription.json"
_OUT = Path(__file__).resolve().parent / "data.js"


def _promo_response(plan: dict) -> dict[str, list[float]]:
    """(a, b) per carried category, from the optimizer's own response model."""
    try:
        from revops.dataio import load
        from revops.optimize.promo import _category_response
        carried = set(plan["plan"]["assortment"]["carried"])
        skus = [s for s in load() if s.sku in carried]
        params = _category_response(skus)
        return {c: [round(float(a), 4), round(float(b), 8)]
                for c, (a, b) in params.items()}
    except Exception:
        return {}


def _assort_by_cat(plan: dict) -> dict[str, dict]:
    """Per-category carried/dropped annual margin — for the assortment bar."""
    try:
        from revops.dataio import load
    except Exception:
        return {}
    carried = set(plan["plan"]["assortment"]["carried"])
    out: dict[str, dict] = {}
    for s in load():
        d = out.setdefault(s.category, {"carried_margin": 0.0,
                                        "dropped_margin": 0.0,
                                        "n_carried": 0, "n_dropped": 0})
        if s.sku in carried:
            d["carried_margin"] += s.annual_margin_eur
            d["n_carried"] += 1
        else:
            d["dropped_margin"] += s.annual_margin_eur
            d["n_dropped"] += 1
    for d in out.values():
        d["carried_margin"] = round(d["carried_margin"], 2)
        d["dropped_margin"] = round(d["dropped_margin"], 2)
    return out


def build() -> Path:
    if not _PLAN.exists():
        raise SystemExit(
            f"{_PLAN} not found — run `python -m revops.report` first.")
    with _PLAN.open(encoding="utf-8") as f:
        plan = json.load(f)

    resp = _promo_response(plan)
    assort = _assort_by_cat(plan)
    budget = plan["plan"]["promo"]["budget_eur"]

    with _OUT.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by web/build_data.py — do not edit by hand.\n")
        f.write("window.PLAN = ")
        json.dump(plan, f, indent=1)
        f.write(";\n")
        f.write("window.PROMO_RESPONSE = ")
        json.dump(resp, f)
        f.write(";\n")
        f.write("window.ASSORT_BY_CAT = ")
        json.dump(assort, f)
        f.write(";\n")
        f.write(f"window.PROMO_BUDGET = {budget};\n")
    return _OUT


if __name__ == "__main__":
    p = build()
    kb = p.stat().st_size / 1024
    print(f"  ok data.js ({kb:.0f} KB) -> {p.relative_to(_ROOT)}")
